name: matrix tests
on:
  push:
  workflow_dispatch:
    inputs:
      logLevel:
        description: 'Log level'
        required: true
        default: 'warning'
        type: choice
        options:
        - info
        - warning
        - debug
      # tags:
      #   description: 'Test scenario tags'
      #   required: false
      #   type: boolean
      # environment:
      #   description: 'Environment to run tests against'
      #   type: environment
      #   required: true

jobs:
  get-changed-next-module-versions:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        module_name: ["module1", "module2"]
    steps:
      - id: checkout-codebase
        name: Checks out the codebase as needed
        uses: actions/checkout@v4
        with:
            fetch-depth: 0
      - id: install_gitversion
        name: Install GitVersion
        uses: gittools/actions/gitversion/setup@v3.2.1
        with:
            versionSpec: '6.2.x'
      - id: version_step_module # step id used as reference for output values
        name: Determine Module Version. Todo is make this dynamic
        uses: gittools/actions/gitversion/execute@v3.2.1
        with:
            # NOTE: Tried specifying a configfile in the module's folder but it does NOT work.
            #   This is the only way it seems to honor using a tag-prefix config value
            overrideConfig: |
                tag-prefix=${{ matrix.module_name }}-
      - id: check_module_version
        name: Debug check of module1's next version to use
        run: |
          echo "Module 1 Next version is ${{ steps.version_step_module.outputs.MajorMinorPatch }}"
      - run: mkdir -p module_versions
      - name: Create a File
        run: echo "${{ matrix.module_name }}-${{ steps.version_step_module.outputs.MajorMinorPatch }}" > module_versions/${{ matrix.module_name }}.txt
      - name: Upload blob report to GitHub Actions Artifacts
        #if: always()
        uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.module_name }}                # artifact reference name - not the filename!
          path: module_versions/${{ matrix.module_name }}.txt    # actual filename and path
          retention-days: 1    # minimum retention
          overwrite: true      # deletes and creates new same named file if found

  # # https://github.com/actions/runner/pull/2477
  # # parallel matrix doesn't yet support dynamic outputs
  # # hence storing individual output in text files and re-joining them later
  merge-module_versions:
    #if: always()
    needs: [get-changed-next-module-versions]
    runs-on: ubuntu-latest
    steps:
      - name: Download blob module_versions from GitHub Actions Artifacts
        uses: actions/download-artifact@v4
        with:
          path: module_versions/
          pattern: module*
          merge-multiple: true
      - run: cat module_versions/module*

