name: matrix tests
on:
  push:
  workflow_dispatch:
    inputs:
      logLevel:
        description: 'Log level'
        required: true
        default: 'warning'
        type: choice
        options:
        - info
        - warning
        - debug
      # tags:
      #   description: 'Test scenario tags'
      #   required: false
      #   type: boolean
      # environment:
      #   description: 'Environment to run tests against'
      #   type: environment
      #   required: true

jobs:
  # test_file:
  #   runs-on: ubuntu-latest
  #   steps:
  #   # works here without codebase checkout?
  #   - run: mkdir -p reports/test
  #   - run: echo hello > reports/test/world.txt
  #   - uses: actions/upload-artifact@v4
  #     with:
  #       name: my-artifact
  #       path: reports/test/world.txt

  run-tests:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        shardIndex: [1, 2, 3, 4]    # trying strings as it doesn't seem to work with integers...
    steps:
      - run: mkdir -p reports
      - name: Create a File
        run: echo "${{ matrix.shardIndex }}" > reports/report-${{ matrix.shardIndex }}.txt
      # Needs to checkout the codebase for the artifact upload to work here. Strange
      #- uses: actions/checkout@v4
      - name: Upload blob report to GitHub Actions Artifacts
        #if: always()
        uses: actions/upload-artifact@v4
        with:
          name: report-${{ matrix.shardIndex }}                # artifact reference name - not the filename!
          path: reports/report-${{ matrix.shardIndex }}.txt    # actual filename and path
          retention-days: 1    # minimum retention
          overwrite: true      # deletes and creates new same named file if found

  merge-reports:
    # Merge reports after run-tests, even if some shards have failed
    #if: always()
    needs: [run-tests]
    runs-on: ubuntu-latest
    steps:
      #- run: mkdir reports
      #- run: echo $PWD
      #- run: ls -la
      #- run: ls -la reports
      
      # Adding this results in the codebase being in DetectChanges/DetectChanges
      #- uses: actions/checkout@v4
      - name: Download blob reports from GitHub Actions Artifacts
        uses: actions/download-artifact@v4
        with:
          path: reports/
          pattern: report-*
          merge-multiple: true
      - run: ls -R *
      - name: Display structure of downloaded files
        run: ls -R *
      - run: ls reports/report-*
      - run: cat reports/report-*

          
      # # https://github.com/actions/runner/pull/2477
      # # parallel matrix doesn't yet support dynamic outputs
      # # hence storing individual output in text files and re-joining them later
      # - uses: actions/upload-artifact@v4
      #   with:
      #     name: analysis-${{ matrix.samples }}.txt
      #     path: .github/scripts/analysis-${{ matrix.samples }}.txt
